// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD16oFotQSMftXbXZgFUC-WGlLfXS9C7V4',
    appId: '1:81993084792:web:668f5842c31aabeb48a28d',
    messagingSenderId: '81993084792',
    projectId: 'todoapp-8d9af',
    authDomain: 'todoapp-8d9af.firebaseapp.com',
    storageBucket: 'todoapp-8d9af.appspot.com',
    measurementId: 'G-KRQGDXYE33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRdHe1rkdg5ja1GP84FipOtlrf4TEfCWM',
    appId: '1:81993084792:android:0b57b1f83430337648a28d',
    messagingSenderId: '81993084792',
    projectId: 'todoapp-8d9af',
    storageBucket: 'todoapp-8d9af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP5Kz7hsRVnjZCt8sCxnxhrxgm7twnS-o',
    appId: '1:81993084792:ios:e0ecb88cd03e305048a28d',
    messagingSenderId: '81993084792',
    projectId: 'todoapp-8d9af',
    storageBucket: 'todoapp-8d9af.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP5Kz7hsRVnjZCt8sCxnxhrxgm7twnS-o',
    appId: '1:81993084792:ios:515fcd68424c6c2548a28d',
    messagingSenderId: '81993084792',
    projectId: 'todoapp-8d9af',
    storageBucket: 'todoapp-8d9af.appspot.com',
    iosBundleId: 'com.example.todoapp.RunnerTests',
  );
}
